smol_path: /Users/riccardo/Desktop/smol_scheduler/demo/GreenHouse.smol
lifted_state_output_path: /Users/riccardo/Desktop/smol_scheduler/demo
lifted_state_output_file: /Users/riccardo/Desktop/smol_scheduler/demo/out.ttl
greenhouse_asset_model_file: /Users/riccardo/Desktop/smol_scheduler/demo/greenhouse.ttl
domain_prefix_uri: http://www.semanticweb.org/gianl/ontologies/2023/1/sirius-greenhouse#
interval_seconds: 60
triplestore_url: http://localhost:3030/GreenHouse

# Paths of data collector config files. They are edited locally and then sent to data collectors.
local_shelf_1_data_collector_config_path: ~/Desktop/smol_scheduler/demo/config_shelf_1.ini
local_shelf_2_data_collector_config_path: ~/Desktop/smol_scheduler/demo/config_shelf_2.ini

# Paths of data collector config files on (remote) data collectors. Files will be sent to these paths.
shelf_1_data_collector_config_path: /home/lab/influx_greenhouse/greenhouse-data-collector/collector/config.ini
shelf_2_data_collector_config_path: /home/lab/influx_greenhouse/greenhouse-data-collector/collector/config.ini
